name: Kotlin CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  release:
    types: [ published ]

jobs:
  build:
    name: Build Mircord.kt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew --stacktrace --info build
  release:
    name: Publish artifacts
    runs-on: ubuntu-latest
    needs: build
    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew --stacktrace --info build
      - name: Publish with Gradle
        run: ./gradlew --no-parallel -x test publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}